name: test-and-build

on:
  push: {}

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    env:
      CGO_ENABLED: 0
      GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 'Lint and test code'
        run: |
          go test -cover -v ./...
          golangci-lint run ./...

      - name: Local Build
        run: go build .

      - name: Trivy Scan
        run: make trivy
